### ISSUE TITLE
Read: open: too many open files

### ISSUE THREAD

**Issue by Jille** [Jille/rufs1#2]
I got this error today: Read: open /full/path/to/file: too many open files (a failing Read RPC to a server node). Master wasn't in that process, so shouldn't be sqlite stuff.

This happened minutes after starting up the program with an old hashcache.dat, so it was likely still hashing files. I don't think it should ever have more than a couple of files open, as we only hash one file in parallel. Maybe Walk() keeps some extra fds open for directories, but that shouldn't get close to any standard limit.

Maybe this was the system limit for open files and the root cause was something else and rufs was just a victim?

**Comment by sgielen** [comment]
1. Readdir: always fanout, remaining peers use the cache if it's not expired (> 30 sec old), remaining peers error/absent
2. Open/Stat: use the cache if it's recent (< 10 sec old), remaining peers fanout, remaining peers error/absent
